### ISSUE TITLE
Is google analytics supported?

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/pytorch_sphinx_theme#109]
The [docs](https://github.com/pytorch/pytorch_sphinx_theme/blob/8eff7df04b7fe5bc5173daa5031b94e062d5fc64/docs/configuring.rst) suggest that GA is supported by this theme, with the `analytics_id` setting.

But I couldn't find any other references to GA in the theme code. I also tried using this option in a  torchvision's PR [`336f95c` (#3660)](https://github.com/pytorch/vision/pull/3660/commits/336f95c7625f73e23232ae774fd28080270668a9) , but looking at the source of the [html rendered  docs](https://510223-73328905-gh.circle-artifacts.com/0/docs/index.html), there doesn't seem to be any mention to GA.

**Comment by NicolasHug** [comment]
Perhaps the fix is as simple as embedding the GA script in https://github.com/pytorch/pytorch_sphinx_theme/blob/55ba50e4dc137728e46d10653ffd5f7ce6c5e424/pytorch_sphinx_theme/layout.html#L77 as done in [`275f166` (#3660)](https://github.com/pytorch/vision/pull/3660/commits/275f166ccfd1dcc3e105fd702f2c07f44fa3324e)

**Comment by brianjo** [comment]
Since this theme is open source, I would prefer we didn't hardcode a GA code into it. We could perhaps drop a generic block in that could be uncommented for those that want to use this method more easily though.

**Comment by NicolasHug** [comment]
Then I would suggest to remove the docs about the `analytics_id` setting altogether.

But the solution proposed in #110 would only embed the GA script if `analytics_id` is manually set - it is excluded otherwise. This is similar to what the ReadTheDocs theme does: https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html#confval-analytics_id
