### ISSUE TITLE
Items on the left do not expand anymore

### ISSUE THREAD

**Issue by ssnl** [pytorch/pytorch_sphinx_theme#12]
<img width="342" alt="screenshot 2018-09-22 14 56 26" src="https://user-images.githubusercontent.com/5674597/45920800-c75dd080-be77-11e8-92c1-c661ac886ed0.png">

There should be sub-items once I click on `torch.nn`.

**Comment by soumith** [comment]
there should be a right-hand menu that should contain the expansions, but looks like that might not be working?

cc: @brucejlin @ericnakagawa

**Comment by brucejlin** [comment]
This appears to have been addressed, or it may have appeared to not be working b/c it is too slow to load - we are exploring fixes now.
