### ISSUE TITLE
 Feature: support ..deprecated Sphinx directive

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/pytorch_sphinx_theme#156]
Same as https://github.com/pytorch/pytorch/issues/73007

The `.. deprecated ::` sphinx directive isn't visible enough in the rendered docs:

```
.. deprecated:: 0.12

    This is deprecated, use blah instead
```

will simply render as:

![image](https://user-images.githubusercontent.com/1190450/154529190-b709ef0d-3e9a-40bd-98db-a6c22adbb33f.png)

Could we make it more obvious, similar to `.. note::` or `.. warning::` ? These are much more visible:

![image](https://user-images.githubusercontent.com/1190450/154529345-5cd164ff-398f-42c4-909c-097459ba49b7.png)

**Comment by ain-soph** [comment]
Is this issue solved yet? If not, I may help.

**Comment by ain-soph** [comment]
My thought is to add a new admonition directive item https://docutils.sourceforge.io/docs/ref/rst/directives.html  
in our theme to overwrite the directive definition in sphinx:  
https://github.com/sphinx-doc/sphinx/blob/13fb17468e547b18b3b8d6b5616ef3d1eb23ac98/sphinx/domains/changeset.py#L147

But I'm not clear what is the expected looking for the new deprecation admonition.

**Comment by pmeier** [comment]
I started, but haven't published anything yet. I can take that up in roughly a month. If you want it earlier, be aware that the deprecated directive is **not** an admonition. Took me quite some time to figure that out.

**Comment by ain-soph** [comment]
Right, I think the sphinx deprecated directive definition is in the previous link I shared, which is not an admonition but a simple directive.

I can solve this issue in recent days, but need to know what's the expected behavior from maintainers.

**Comment by NicolasHug** [comment]
Thanks for your interest in this issue @ain-soph. I think that making it look like a `.. warning` (replacing "WARNING" with "DEPRECATION") would be a good start.
We can bike-shed on the color afterward :)

**Comment by ain-soph** [comment]
@NicolasHug Then the admonition should be `.. deprecated` or `.. deprecation` since the text is `DEPRECATION`?

**Comment by NicolasHug** [comment]
I'm hoping that the text of the headline is independent of the name of the directive?

It should still be `.. deprecated`, since it's a sphinx built-in directive. The key here is to change how it renders with the pytorch-sphinx-theme.

**Comment by ain-soph** [comment]
Got it. That makes sense. I'll get the example soon.

**Comment by ain-soph** [comment]
@NicolasHug  
I first tested at my own theme repo.  
The commit is https://github.com/ain-soph/trojanzoo_sphinx_theme/commit/e8444f86d62ea749ed285f381eea0afe07a5c246  
The generated docs is https://ain-soph.github.io/trojanzoo_sphinx_theme/demo/demo.html#admonitions  
The example figure is ![image](https://user-images.githubusercontent.com/13214530/178361645-14279ac1-2dca-456e-871f-d1cf4ebaced2.png)

**Comment by ain-soph** [comment]
According to the internal chat with @NicolasHug , we don't want a new admonition any longer.  
Instead, we just want to modify the current looking to keep it similar as behaved in [sklearn](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.ElasticNet.html?highlight=elasticnet#sklearn.linear_model.ElasticNet)

The current looking after the new PR:

![image](https://user-images.githubusercontent.com/13214530/178814329-b5a316f3-b334-4002-8996-656b320ece45.png)

**Comment by adamjstewart** [comment]
Since we also use this theme in [TorchGeo](https://torchgeo.readthedocs.io/en/stable/), @ain-soph asked me to share my opinion on this discussion.

In terms of syntax, we definitely want to stick with the builtin [directive](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#paragraph-level-markup):
```rst
.. deprecated:: 3.1
   Use :func:`spam` instead.
```
We don't want to create our own custom admonition for this. This is important if, e.g., we want to switch to a new theme someday. We want to make sure we use a directive that all themes support so as to avoid straying further from other themes. We use this same directive in TorchGeo already.

In terms of appearance, I do have a slight preference for the appearance of warning. If we can keep the same rST syntax but use an appearance similar to warning that would be ideal to me. We should still include the version in which the feature is deprecated, and maybe a way to document when the feature is planned for removal?

**Comment by ain-soph** [comment]
@adamjstewart I completely agree with you that it should NOT raise any concern during switching themes. We should definitely avoid the articulation cost.

For the appearance, what's your expected looking?

```
.. deprecated:: 3.0
   This is deprecated since 3.0
```

Is it something like this?

![image](https://user-images.githubusercontent.com/13214530/178915615-ae8e2eb6-ea16-4390-b588-05e9bc048013.png)

If so, I'm afraid that we still need to create a new custom admonition. But for theme users, they should feel no difference when coding the documents.

-----------------------------------------------------------------

If we stick to the sphinx `deprecated` directive that is actually a changeset, the only thing we can do is quite limited (just like sklearn does): add a colorful bbox in css.

**Comment by NicolasHug** [comment]
Thanks a lot @ain-soph , the renderring in  https://github.com/pytorch/pytorch_sphinx_theme/issues/156#issuecomment-1183589446 looks infinitely better than what we currently have, so LGTM. We can always improve / change how it looks later if we feel like it.
