### ISSUE TITLE
Reuse for PyTorch project

### ISSUE THREAD

**Issue by Borda** [pytorch/pytorch_sphinx_theme#61]
Hello, I would be interested in some kind of guide how we could reuse this cool theme also for Lightning (which belongs now to PyTorch ecosystem). In particular, I would like to ask how to re=maps paths from top and bottom navigation and/or how to drop some options from these navigations?

https://github.com/williamFalcon/pytorch-lightning/pull/521

**Comment by arzoo14** [comment]
@Borda 
Can you please explain how you used pytorch_sphinx_theme into your project?
